name: login_widget
description: A Flutter package capable of streamlining the construction of login forms.
version: 1.0.3
repository: https://www.github.com/tytydraco/login_widget

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
